IncIncEntityFramework/Models/ErrorViewModel.cs
using System;

namespace IncIncEntityFramework.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

IncIncEntityFramework/Models/PieceWorkerModel.cs
//PieceWorkerModel.cs
//Author: Shweta Patel [Reference: Kyle chapman]
//created: November 20
//model to  desescribing data for a piece worker for INC
//Includes DataAnotation for validation and intened to be used with entity Framework

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace IncIncEntityFramework.Models
{
    public class PieceWorkerModel
    {
        /// <summary>
        /// Arbitrary ID for use with Entity Framework. 
        /// </summary>
        public int ID { get; set; }

        /// <summary>
        /// worker's First name
        /// </summary>
        [Required(AllowEmptyStrings = false, ErrorMessage = "You must enter a first name")]
        [Display(Name = "First Name")]
        public string FirstName { get; set; }

        /// <summary>
        /// worker's Last name
        /// </summary>
        [Required(AllowEmptyStrings = false, ErrorMessage = "You must enter a last name")]
        [Display(Name = "last Name")]
        public string LastName { get; set; }
        /// <summary>
        /// Message
        /// </summary>
        [Required(AllowEmptyStrings = false, ErrorMessage = "You must enter a Message")]
        [Range(1, 15000, ErrorMessage = "The message is must be between 1 to 15000")]
        [Display(Name = "Message")]
        public int Message { get; set; }

        /// <summary>
        /// Is worker is senior or not? 
        /// </summary>
        [Display(Name ="Senior Worker")]
        public bool IsSenior { get; set; }
        /// <summary>
        /// To display last updated date
        /// </summary>
        [Display(Name = "Last Updated Date")]
        public DateTime LastUpdated { get; set; }

        /// <summary>
        /// The Getpay() method is used to calculate a worker's pay using their pay rate and Message sent.
        /// </summary>
        /// <returns></returns>
        public virtual decimal Getpay()
        {

            decimal employeePay = 0M;

            // Arrays used for comparisons to determine the pay rate.
            int[] messageThresholds = new int[] { 1250, 2500, 3750, 5000 };
            decimal[] payRates = new decimal[] { 0.025M, 0.03M, 0.035M, 0.041M, 0.048M };

            // Comparisons to determine the pay rate.
            if (Message < messageThresholds[0])
            {
                employeePay = Message * payRates[0];
            }
            else if (Message < messageThresholds[1])
            {
                employeePay = Message * payRates[1];
            }
            else if (Message < messageThresholds[2])
            {
                employeePay = Message * payRates[2];
            }
            else if (Message < messageThresholds[3])
            {
                employeePay = Message * payRates[3];
            }
            else
            {
                employeePay = Message * payRates[4];
            }

            return employeePay;
        }
    }
}

IncIncEntityFramework/Controllers/HomeController.cs
using IncIncEntityFramework.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace IncIncEntityFramework.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

IncIncEntityFramework/Controllers/WorkersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using IncIncEntityFramework.Contexts;
using IncIncEntityFramework.Models;

namespace IncIncEntityFramework.Controllers
{
    public class WorkersController : Controller
    {
        private readonly WorkerContext _context;

        public WorkersController(WorkerContext context)
        {
            _context = context;
        }

        // GET: Workers
        public async Task<IActionResult> Index()
        {
            return View(await _context.Workers.ToListAsync());
        }

        // GET: Workers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pieceWorkerModel = await _context.Workers
                .FirstOrDefaultAsync(m => m.ID == id);
            if (pieceWorkerModel == null)
            {
                return NotFound();
            }

            return View(pieceWorkerModel);
        }

        // GET: Workers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Workers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,FirstName,LastName,Message")] PieceWorkerModel pieceWorkerModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(pieceWorkerModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(pieceWorkerModel);
        }

        // GET: Workers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pieceWorkerModel = await _context.Workers.FindAsync(id);
            if (pieceWorkerModel == null)
            {
                return NotFound();
            }
            return View(pieceWorkerModel);
        }

        // POST: Workers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,FirstName,LastName,Message")] PieceWorkerModel pieceWorkerModel)
        {
            if (id != pieceWorkerModel.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(pieceWorkerModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PieceWorkerModelExists(pieceWorkerModel.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(pieceWorkerModel);
        }

        // GET: Workers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pieceWorkerModel = await _context.Workers
                .FirstOrDefaultAsync(m => m.ID == id);
            if (pieceWorkerModel == null)
            {
                return NotFound();
            }

            return View(pieceWorkerModel);
        }

        // POST: Workers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var pieceWorkerModel = await _context.Workers.FindAsync(id);
            _context.Workers.Remove(pieceWorkerModel);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PieceWorkerModelExists(int id)
        {
            return _context.Workers.Any(e => e.ID == id);
        }
    }
}

IncIncEntityFramework/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

IncIncEntityFramework/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Incorporeal Incorporated </title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-info bg-info border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Incorporeal Incorporated</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-warning" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-warning" asp-area="" asp-controller="Workers" asp-action="Index">Worker List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-warning" asp-area="" asp-controller="Workers" asp-action="Create">Create Worker</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Incorporeal Incorporated - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

IncIncEntityFramework/Views/Workers/Create.cshtml
@model IncIncEntityFramework.Models.PieceWorkerModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Message" class="control-label"></label>
                <input asp-for="Message" class="form-control" />
                <span asp-validation-for="Message" class="text-danger"></span>
            </div>

            <div class="form-group form-check">
                @*<label class="form-check-label">
            <input class="form-check-input" asp-for="IsSenior" />
            @Html.DisplayNameFor(Model => Model.IsSenior)
        </label>*@
                @Html.RadioButtonFor(m => m.IsSenior, false, new { @checked = true }) Senior Worker<br />
                @Html.RadioButtonFor(m => m.IsSenior, true)Pieces Worker
            </div>

            @*<div class="form-group">
                @Html.LabelFor(model => model.LastUpdated, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.LastUpdated, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.LastUpdated, "", new { @class = "text-danger" })
                </div>
            </div>*@
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

IncIncEntityFramework/Views/Workers/Delete.cshtml
@model IncIncEntityFramework.Models.PieceWorkerModel

@{
    ViewData["Title"] = "Delete";
}

<h1 style="color:lightcoral">Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Message)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Message)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

IncIncEntityFramework/Views/Workers/Details.cshtml
@model IncIncEntityFramework.Models.PieceWorkerModel

@{
    ViewData["Title"] = "Details";
}

<h1 style="color:lightcoral">Details</h1>

<div>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Message)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Message)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IsSenior)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IsSenior)
        </dd>
        <dt class="col-sm-2">
            Calculated Pay
        </dt>
        <dd class="col-sm-10">
            @Model.Getpay().ToString("c")
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

IncIncEntityFramework/Views/Workers/Edit.cshtml
@model IncIncEntityFramework.Models.PieceWorkerModel

@{
    ViewData["Title"] = "Edit";
}

<h1 style="color:lightcoral">Edit</h1>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Message" class="control-label"></label>
                <input asp-for="Message" class="form-control" />
                <span asp-validation-for="Message" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsSenior" />
                    @Html.DisplayNameFor(Model => Model.IsSenior)
                </label>
            </div>
                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-primary" />
                </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

IncIncEntityFramework/Views/Workers/Index.cshtml
@model IEnumerable<IncIncEntityFramework.Models.PieceWorkerModel>

@{
    ViewData["Title"] = "Worker List";
    int totalWorkers = 0;
    int totalMessage = 0;
    decimal totalPay = 0;
    decimal averagePay;

}

<h1 style="color:lightcoral">Worker List</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table" style="background-color: #e3f2fd">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Message)
            </th>
            <th>
                Worker Type:
            </th>
            <th>
                Calculated Pay:
            </th>
            <th>
                Updated Date-Time:
            </th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            totalWorkers++;
            totalMessage += item.Message;
            totalPay += item.Getpay();

        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Message)
            </td>
            @if (item.IsSenior)
            {
                <td>
                    Senior Worker
                </td>
            }
            else
            {
                <td>
                    Pieces Worker
                </td>
            }
            <td>
                @item.Getpay().ToString("c")
            </td>
            <td>
                @Html.DisplayFor(modelItem => DateTime.Now)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
            </td>
        </tr>
        }
    </tbody>
</table>

@if (totalWorkers > 0)
{

    averagePay = totalPay / totalWorkers;

<div class="col-md-6 offset-3" style="background-color: #f3dfdf">
    <p>
        Total Workers: @totalWorkers
    </p>
    <p>
        Total Message: @totalMessage
    </p>
    <p>
        Total Pay: @totalPay.ToString("c")
    </p>
    <p>
        Average Pay: @averagePay.ToString("c")
    </p>

</div>


}